### ISSUE TITLE
Dead image links in blog

### ISSUE THREAD

**Issue by genovese** [AlgebraicJulia/algebraicjulia.org#38]
There are dead image links in several blog posts linked from the landing page.  For example, the Graphs and C-sets series of posts, the svgs that are linked to `_svgs/*.svg` are not found. (These particular examples illustrate the schemas being discussed.) All the missing links have this form, suggesting that the `_svgs` directory has been moved or not built.

See for instance https://blog.algebraicjulia.org/post/2020/09/cset-graphs-1/.

Thanks

**Comment by epatters** [comment]
Thanks for letting us know! It is probably due to a change in how we're converting the LaTeX diagrams to SVG.

**Comment by mehalter** [comment]
This should be resolved now! Thanks again for reporting!
